//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logger.ConfigurationSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameGeometry", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameGeometry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BallRadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldRadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GateWidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BallRadius {
            get {
                return this.BallRadiusField;
            }
            set {
                if ((this.BallRadiusField.Equals(value) != true)) {
                    this.BallRadiusField = value;
                    this.RaisePropertyChanged("BallRadius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldRadius {
            get {
                return this.FieldRadiusField;
            }
            set {
                if ((this.FieldRadiusField.Equals(value) != true)) {
                    this.FieldRadiusField = value;
                    this.RaisePropertyChanged("FieldRadius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GateWidth {
            get {
                return this.GateWidthField;
            }
            set {
                if ((this.GateWidthField.Equals(value) != true)) {
                    this.GateWidthField = value;
                    this.RaisePropertyChanged("GateWidth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameTimings", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameTimings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BeforeStartTimeoutLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GameStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeLengthSecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeOutLengthSecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BeforeStartTimeoutLength {
            get {
                return this.BeforeStartTimeoutLengthField;
            }
            set {
                if ((this.BeforeStartTimeoutLengthField.Equals(value) != true)) {
                    this.BeforeStartTimeoutLengthField = value;
                    this.RaisePropertyChanged("BeforeStartTimeoutLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GameStartDate {
            get {
                return this.GameStartDateField;
            }
            set {
                if ((this.GameStartDateField.Equals(value) != true)) {
                    this.GameStartDateField = value;
                    this.RaisePropertyChanged("GameStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeCount {
            get {
                return this.TimeCountField;
            }
            set {
                if ((this.TimeCountField.Equals(value) != true)) {
                    this.TimeCountField = value;
                    this.RaisePropertyChanged("TimeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeLengthSec {
            get {
                return this.TimeLengthSecField;
            }
            set {
                if ((this.TimeLengthSecField.Equals(value) != true)) {
                    this.TimeLengthSecField = value;
                    this.RaisePropertyChanged("TimeLengthSec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeOutLengthSec {
            get {
                return this.TimeOutLengthSecField;
            }
            set {
                if ((this.TimeOutLengthSecField.Equals(value) != true)) {
                    this.TimeOutLengthSecField = value;
                    this.RaisePropertyChanged("TimeOutLengthSec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameMembership", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameMembership : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Logger.ConfigurationSvc.TeamMembership> TeamsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamCount {
            get {
                return this.TeamCountField;
            }
            set {
                if ((this.TeamCountField.Equals(value) != true)) {
                    this.TeamCountField = value;
                    this.RaisePropertyChanged("TeamCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Logger.ConfigurationSvc.TeamMembership> Teams {
            get {
                return this.TeamsField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamsField, value) != true)) {
                    this.TeamsField = value;
                    this.RaisePropertyChanged("Teams");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamMembership", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TeamMembership : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ControlCenterCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Logger.ConfigurationSvc.ControllCenterData> ControlCentersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte GateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Logger.ConfigurationSvc.PlayerData> PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TeamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ControlCenterCount {
            get {
                return this.ControlCenterCountField;
            }
            set {
                if ((this.ControlCenterCountField.Equals(value) != true)) {
                    this.ControlCenterCountField = value;
                    this.RaisePropertyChanged("ControlCenterCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Logger.ConfigurationSvc.ControllCenterData> ControlCenters {
            get {
                return this.ControlCentersField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlCentersField, value) != true)) {
                    this.ControlCentersField = value;
                    this.RaisePropertyChanged("ControlCenters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte GateId {
            get {
                return this.GateIdField;
            }
            set {
                if ((this.GateIdField.Equals(value) != true)) {
                    this.GateIdField = value;
                    this.RaisePropertyChanged("GateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerCount {
            get {
                return this.PlayerCountField;
            }
            set {
                if ((this.PlayerCountField.Equals(value) != true)) {
                    this.PlayerCountField = value;
                    this.RaisePropertyChanged("PlayerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Logger.ConfigurationSvc.PlayerData> Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControllCenterData", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ControllCenterData : Logger.ConfigurationSvc.UnitData {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerData", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PlayerData : Logger.ConfigurationSvc.UnitData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte MachineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Logger.ConfigurationSvc.Color MarkerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarkerPositionXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarkerPositionYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MachineId {
            get {
                return this.MachineIdField;
            }
            set {
                if ((this.MachineIdField.Equals(value) != true)) {
                    this.MachineIdField = value;
                    this.RaisePropertyChanged("MachineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Logger.ConfigurationSvc.Color Marker {
            get {
                return this.MarkerField;
            }
            set {
                if ((this.MarkerField.Equals(value) != true)) {
                    this.MarkerField = value;
                    this.RaisePropertyChanged("Marker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarkerPositionX {
            get {
                return this.MarkerPositionXField;
            }
            set {
                if ((this.MarkerPositionXField.Equals(value) != true)) {
                    this.MarkerPositionXField = value;
                    this.RaisePropertyChanged("MarkerPositionX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarkerPositionY {
            get {
                return this.MarkerPositionYField;
            }
            set {
                if ((this.MarkerPositionYField.Equals(value) != true)) {
                    this.MarkerPositionYField = value;
                    this.RaisePropertyChanged("MarkerPositionY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitData", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Logger.ConfigurationSvc.PlayerData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Logger.ConfigurationSvc.ControllCenterData))]
    public partial class UnitData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TeamIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    [System.SerializableAttribute()]
    public partial struct Color : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short knownColorField;
        
        private string nameField;
        
        private short stateField;
        
        private long valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short knownColor {
            get {
                return this.knownColorField;
            }
            set {
                if ((this.knownColorField.Equals(value) != true)) {
                    this.knownColorField = value;
                    this.RaisePropertyChanged("knownColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameRules", Namespace="http://schemas.datacontract.org/2004/07/Configuration.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameRules : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationSvc.IConfigurationManager")]
    public interface IConfigurationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationManager/COnfigurationIsReady", ReplyAction="http://tempuri.org/IConfigurationManager/COnfigurationIsReadyResponse")]
        bool COnfigurationIsReady();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationManager/COnfigurationIsReady", ReplyAction="http://tempuri.org/IConfigurationManager/COnfigurationIsReadyResponse")]
        System.Threading.Tasks.Task<bool> COnfigurationIsReadyAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationManagerChannel : Logger.ConfigurationSvc.IConfigurationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationManagerClient : System.ServiceModel.ClientBase<Logger.ConfigurationSvc.IConfigurationManager>, Logger.ConfigurationSvc.IConfigurationManager {
        
        public ConfigurationManagerClient() {
        }
        
        public ConfigurationManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool COnfigurationIsReady() {
            return base.Channel.COnfigurationIsReady();
        }
        
        public System.Threading.Tasks.Task<bool> COnfigurationIsReadyAsync() {
            return base.Channel.COnfigurationIsReadyAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationSvc.IGeometryManager")]
    public interface IGeometryManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeometryManager/SetGameGeometry", ReplyAction="http://tempuri.org/IGeometryManager/SetGameGeometryResponse")]
        void SetGameGeometry(Logger.ConfigurationSvc.GameGeometry geometry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeometryManager/SetGameGeometry", ReplyAction="http://tempuri.org/IGeometryManager/SetGameGeometryResponse")]
        System.Threading.Tasks.Task SetGameGeometryAsync(Logger.ConfigurationSvc.GameGeometry geometry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeometryManager/GetGameGeometry", ReplyAction="http://tempuri.org/IGeometryManager/GetGameGeometryResponse")]
        Logger.ConfigurationSvc.GameGeometry GetGameGeometry();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeometryManager/GetGameGeometry", ReplyAction="http://tempuri.org/IGeometryManager/GetGameGeometryResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameGeometry> GetGameGeometryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeometryManagerChannel : Logger.ConfigurationSvc.IGeometryManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeometryManagerClient : System.ServiceModel.ClientBase<Logger.ConfigurationSvc.IGeometryManager>, Logger.ConfigurationSvc.IGeometryManager {
        
        public GeometryManagerClient() {
        }
        
        public GeometryManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeometryManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeometryManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeometryManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetGameGeometry(Logger.ConfigurationSvc.GameGeometry geometry) {
            base.Channel.SetGameGeometry(geometry);
        }
        
        public System.Threading.Tasks.Task SetGameGeometryAsync(Logger.ConfigurationSvc.GameGeometry geometry) {
            return base.Channel.SetGameGeometryAsync(geometry);
        }
        
        public Logger.ConfigurationSvc.GameGeometry GetGameGeometry() {
            return base.Channel.GetGameGeometry();
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameGeometry> GetGameGeometryAsync() {
            return base.Channel.GetGameGeometryAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationSvc.ITimingManager")]
    public interface ITimingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingManager/SetGameTimings", ReplyAction="http://tempuri.org/ITimingManager/SetGameTimingsResponse")]
        void SetGameTimings(Logger.ConfigurationSvc.GameTimings timings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingManager/SetGameTimings", ReplyAction="http://tempuri.org/ITimingManager/SetGameTimingsResponse")]
        System.Threading.Tasks.Task SetGameTimingsAsync(Logger.ConfigurationSvc.GameTimings timings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingManager/GetGameTimings", ReplyAction="http://tempuri.org/ITimingManager/GetGameTimingsResponse")]
        Logger.ConfigurationSvc.GameTimings GetGameTimings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingManager/GetGameTimings", ReplyAction="http://tempuri.org/ITimingManager/GetGameTimingsResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameTimings> GetGameTimingsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimingManagerChannel : Logger.ConfigurationSvc.ITimingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimingManagerClient : System.ServiceModel.ClientBase<Logger.ConfigurationSvc.ITimingManager>, Logger.ConfigurationSvc.ITimingManager {
        
        public TimingManagerClient() {
        }
        
        public TimingManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimingManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimingManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimingManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetGameTimings(Logger.ConfigurationSvc.GameTimings timings) {
            base.Channel.SetGameTimings(timings);
        }
        
        public System.Threading.Tasks.Task SetGameTimingsAsync(Logger.ConfigurationSvc.GameTimings timings) {
            return base.Channel.SetGameTimingsAsync(timings);
        }
        
        public Logger.ConfigurationSvc.GameTimings GetGameTimings() {
            return base.Channel.GetGameTimings();
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameTimings> GetGameTimingsAsync() {
            return base.Channel.GetGameTimingsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationSvc.IMembershipManager")]
    public interface IMembershipManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipManager/GetMembership", ReplyAction="http://tempuri.org/IMembershipManager/GetMembershipResponse")]
        Logger.ConfigurationSvc.GameMembership GetMembership();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipManager/GetMembership", ReplyAction="http://tempuri.org/IMembershipManager/GetMembershipResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameMembership> GetMembershipAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipManager/GetTeam", ReplyAction="http://tempuri.org/IMembershipManager/GetTeamResponse")]
        Logger.ConfigurationSvc.TeamMembership GetTeam(byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipManager/GetTeam", ReplyAction="http://tempuri.org/IMembershipManager/GetTeamResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.TeamMembership> GetTeamAsync(byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipManager/GetPalyer", ReplyAction="http://tempuri.org/IMembershipManager/GetPalyerResponse")]
        Logger.ConfigurationSvc.PlayerData GetPalyer(byte PlayerId, byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipManager/GetPalyer", ReplyAction="http://tempuri.org/IMembershipManager/GetPalyerResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.PlayerData> GetPalyerAsync(byte PlayerId, byte TeamId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMembershipManagerChannel : Logger.ConfigurationSvc.IMembershipManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MembershipManagerClient : System.ServiceModel.ClientBase<Logger.ConfigurationSvc.IMembershipManager>, Logger.ConfigurationSvc.IMembershipManager {
        
        public MembershipManagerClient() {
        }
        
        public MembershipManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MembershipManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembershipManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembershipManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Logger.ConfigurationSvc.GameMembership GetMembership() {
            return base.Channel.GetMembership();
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameMembership> GetMembershipAsync() {
            return base.Channel.GetMembershipAsync();
        }
        
        public Logger.ConfigurationSvc.TeamMembership GetTeam(byte TeamId) {
            return base.Channel.GetTeam(TeamId);
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.TeamMembership> GetTeamAsync(byte TeamId) {
            return base.Channel.GetTeamAsync(TeamId);
        }
        
        public Logger.ConfigurationSvc.PlayerData GetPalyer(byte PlayerId, byte TeamId) {
            return base.Channel.GetPalyer(PlayerId, TeamId);
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.PlayerData> GetPalyerAsync(byte PlayerId, byte TeamId) {
            return base.Channel.GetPalyerAsync(PlayerId, TeamId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationSvc.IMembershipSetup")]
    public interface IMembershipSetup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipSetup/RegisterTeam", ReplyAction="http://tempuri.org/IMembershipSetup/RegisterTeamResponse")]
        Logger.ConfigurationSvc.TeamMembership RegisterTeam(byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipSetup/RegisterTeam", ReplyAction="http://tempuri.org/IMembershipSetup/RegisterTeamResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.TeamMembership> RegisterTeamAsync(byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipSetup/RegisterRobot", ReplyAction="http://tempuri.org/IMembershipSetup/RegisterRobotResponse")]
        Logger.ConfigurationSvc.PlayerData RegisterRobot(byte PlayerId, byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipSetup/RegisterRobot", ReplyAction="http://tempuri.org/IMembershipSetup/RegisterRobotResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.PlayerData> RegisterRobotAsync(byte PlayerId, byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipSetup/UnRegisterRobot", ReplyAction="http://tempuri.org/IMembershipSetup/UnRegisterRobotResponse")]
        void UnRegisterRobot(byte PlayerId, byte TeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipSetup/UnRegisterRobot", ReplyAction="http://tempuri.org/IMembershipSetup/UnRegisterRobotResponse")]
        System.Threading.Tasks.Task UnRegisterRobotAsync(byte PlayerId, byte TeamId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMembershipSetupChannel : Logger.ConfigurationSvc.IMembershipSetup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MembershipSetupClient : System.ServiceModel.ClientBase<Logger.ConfigurationSvc.IMembershipSetup>, Logger.ConfigurationSvc.IMembershipSetup {
        
        public MembershipSetupClient() {
        }
        
        public MembershipSetupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MembershipSetupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembershipSetupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembershipSetupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Logger.ConfigurationSvc.TeamMembership RegisterTeam(byte TeamId) {
            return base.Channel.RegisterTeam(TeamId);
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.TeamMembership> RegisterTeamAsync(byte TeamId) {
            return base.Channel.RegisterTeamAsync(TeamId);
        }
        
        public Logger.ConfigurationSvc.PlayerData RegisterRobot(byte PlayerId, byte TeamId) {
            return base.Channel.RegisterRobot(PlayerId, TeamId);
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.PlayerData> RegisterRobotAsync(byte PlayerId, byte TeamId) {
            return base.Channel.RegisterRobotAsync(PlayerId, TeamId);
        }
        
        public void UnRegisterRobot(byte PlayerId, byte TeamId) {
            base.Channel.UnRegisterRobot(PlayerId, TeamId);
        }
        
        public System.Threading.Tasks.Task UnRegisterRobotAsync(byte PlayerId, byte TeamId) {
            return base.Channel.UnRegisterRobotAsync(PlayerId, TeamId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationSvc.IRuleManager")]
    public interface IRuleManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleManager/SetGameRules", ReplyAction="http://tempuri.org/IRuleManager/SetGameRulesResponse")]
        void SetGameRules(Logger.ConfigurationSvc.GameRules rules);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleManager/SetGameRules", ReplyAction="http://tempuri.org/IRuleManager/SetGameRulesResponse")]
        System.Threading.Tasks.Task SetGameRulesAsync(Logger.ConfigurationSvc.GameRules rules);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleManager/GetGameRules", ReplyAction="http://tempuri.org/IRuleManager/GetGameRulesResponse")]
        Logger.ConfigurationSvc.GameRules GetGameRules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleManager/GetGameRules", ReplyAction="http://tempuri.org/IRuleManager/GetGameRulesResponse")]
        System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameRules> GetGameRulesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRuleManagerChannel : Logger.ConfigurationSvc.IRuleManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleManagerClient : System.ServiceModel.ClientBase<Logger.ConfigurationSvc.IRuleManager>, Logger.ConfigurationSvc.IRuleManager {
        
        public RuleManagerClient() {
        }
        
        public RuleManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetGameRules(Logger.ConfigurationSvc.GameRules rules) {
            base.Channel.SetGameRules(rules);
        }
        
        public System.Threading.Tasks.Task SetGameRulesAsync(Logger.ConfigurationSvc.GameRules rules) {
            return base.Channel.SetGameRulesAsync(rules);
        }
        
        public Logger.ConfigurationSvc.GameRules GetGameRules() {
            return base.Channel.GetGameRules();
        }
        
        public System.Threading.Tasks.Task<Logger.ConfigurationSvc.GameRules> GetGameRulesAsync() {
            return base.Channel.GetGameRulesAsync();
        }
    }
}
